class RealEstate: ...
class SavingAccount: ...
class CheckingAccount: ...
class Stock: ...
class Bond: ...

class BankAccount(SavingAccount, CheckingAccount): ...
class Security(Stock, Bond): ...

class InterestBearingItem(BankAccount, Security): ...

class InsurableItem(RealEstate, BankAccount): ...
class Asset(RealEstate, BankAccount, Security): ...